Create geant4.scm with Geant4 from CERN
guix-science/guix-science pull request #4
Opened 2021-03-04 13:47 UTC by PandaGix

Geant4 uses their own licence https://geant4.web.cern.ch/license/LICENSE.html, which allows redistribution under some conditions, and seems to meet the definition of a free software license. This may be solved by adding a costom license.scm file for guix-science.

2021-03-05 07:37 UTC, PromyLOPh commented
Did you email licensing@fsf.org and ask them about the custom license as suggested on guix-devel@gnu.org? What was the result?

2021-03-12 14:22 UTC, PandaGix commented
Still waiting for reply......

2021-03-18 13:20 UTC, PromyLOPh requested changes

2021-03-18 13:20 UTC, PromyLOPh commented on guix-science/packages/geant4.scm
> +    ;;(license license:g4sl1.0) ; to be added in licences
Could you add this license please?

2021-03-18 13:20 UTC, PromyLOPh commented on guix-science/packages/geant4.scm
> +    (arguments `(
Please use Guix’ parethesis style.

2021-03-18 13:20 UTC, PromyLOPh commented on guix-science/packages/geant4.scm
> +            (let* (
Is it possible to symlink these? Or does the software support a variable that points to one/multiple data directories?

2024-04-16 20:17 UTC, rekado commented
I'm closing this because geant4 is now part of guix-science-nonfree: https://github.com/guix-science/guix-science-nonfree/commit/26a865d435102fd8f02c9324392752ff51109cd5

Thank you!

2024-04-16 20:17 UTC, closed without merging